# API Keys Configuration
# DO NOT commit this file to version control!
# Add this file to .gitignore

NEWS_API_KEY=8dfa263dbda54585bd3b62034f533f59
GEMINI_API_KEY=AIzaSyDMlGKGqx7Ci1TD7XCF8lin_f0y3SXiQsw
